[package]
name = "rust-hello"
version = "0.0.1"
edition = "2021"

[dependencies]
panic-halt = "1.0.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"  # Optimize for size
lto = true
strip = true

[build-dependencies]
bindgen = "0.71.0"
